name = "kalyswap-api"
type = "javascript"
workers_dev = false
account_id = "5cca3f11fc10e5dd2b5914005aa8f405"
zone_id = "89d3d4d0f53275c09563aa791b8d6bd4"
route = "api.kalyswap.io/*"
kv_namespaces = [
  { binding = "CHEF_LP_TOKENS", preview_id = "1fd795d0411c4b799b3093e98ceb853f", id = "988cdad7e92946f6864348491b662e3a" },
  { binding = "REWARDER_VIA_MULTIPLIER", preview_id = "12ca17f5e01748448f2eaeae90db0d42", id = "1ef86bbdaa4e4d21ac52afb67fb202ed" }
]
compatibility_date = "2023-08-08"

[build]
command = "yarn run build"

[build.upload]
format = "service-worker"
