name = "kalyswap-api"
type = "javascript"
workers_dev = true
account_id = "d348270f8966f389642edf737e7d8d3c"
kv_namespaces = [
  { binding = "CHEF_LP_TOKENS", preview_id = "25eeef6470544ffd98d91cb3d064d104", id = "81c214b2b48c481f96bb86cf05689590" },
  { binding = "REWARDER_VIA_MULTIPLIER", preview_id = "398c2f8ba3ec4df2bb060370b0e04b05", id = "e87c2875302b47bab45c0f8ec085e3bd" }
]
compatibility_date = "2022-08-09"

[build]
command = "yarn run build"

[build.upload]
format = "service-worker"
